#!/usr/bin/env node
/* Build a static data file for a tournament whose schedule is NOT a public Google Sheet
   (an Excel file from OneDrive, a PDF you re-typed into a spreadsheet, etc.).

   1. Save every division tab as its own CSV (File > Download > CSV in Sheets/Excel).
      Name each file after the tab, e.g. "10U Boys.csv", plus optionally "Teams Entered.csv".
   2. Run:  node tools/import-static.js <tournament-id> <csv-directory> --start YYYY-MM-DD [--layout sheet-tabs|sheet-southcoast]
   3. The script writes data/<tournament-id>.js. In data/manifest.js set
        source: { type: 'static' }
      for that tournament and the app will load the file instead of a live sheet.
   Re-run the script whenever you get a fresh copy of the schedule. */
const fs = require('fs'), path = require('path');
require('../src/model.js');
const adapters = { 'sheet-tabs': require('../src/adapters/sheet-tabs.js'), 'sheet-southcoast': require('../src/adapters/sheet-southcoast.js') };

const [id, dir, ...rest] = process.argv.slice(2);
const opt = (k, d) => { const i = rest.indexOf('--' + k); return i >= 0 ? rest[i + 1] : d; };
if (!id || !dir) { console.error('usage: node tools/import-static.js <tournament-id> <csv-directory> --start YYYY-MM-DD [--layout sheet-tabs]'); process.exit(1); }
const layout = opt('layout', 'sheet-tabs'), start = opt('start', null);
const adapter = adapters[layout];
if (!adapter) { console.error('unknown layout', layout); process.exit(1); }

const files = fs.readdirSync(dir).filter(f => f.toLowerCase().endsWith('.csv')).sort();
const csv = {};
files.forEach(f => { csv[f.replace(/\.csv$/i, '')] = fs.readFileSync(path.join(dir, f), 'utf8'); });
const teamsTab = Object.keys(csv).find(k => /teams?\s*entered|entries/i.test(k)) || null;
const tabs = Object.keys(csv).filter(k => k !== teamsTab);
const cfg = layout === 'sheet-tabs' ? { tabs, teamsTab, startDate: start } : { tab: tabs[0], startDate: start };
const model = adapter.build(csv, cfg);
model.generated = new Date().toISOString();
const out = path.join(__dirname, '..', 'data', id + '.js');
fs.writeFileSync(out, `// Generated by tools/import-static.js on ${model.generated} from ${files.length} CSV file(s).\nwindow.POLO_STATIC = window.POLO_STATIC || {};\nwindow.POLO_STATIC[${JSON.stringify(id)}] = ${JSON.stringify(model)};\n`);
console.log(`wrote ${out}: ${model.divisions.length} divisions, ${model.divisions.reduce((n, d) => n + d.games.length, 0)} games`);
if (model.notes.length) console.log('notes:', model.notes.join('\n  '));
